export const GET_LATEST_CLASS_ID_REQUEST = 'GET_LATEST_CLASS_ID_REQUEST';
export const GET_LATEST_CLASS_ID_SUCCESS = 'GET_LATEST_CLASS_ID_SUCCESS';
export const GET_LATEST_CLASS_ID_FAILURE = 'GET_LATEST_CLASS_ID_FAILURE';

export const GET_CLASS_BY_ID_REQUEST = 'GET_CLASS_BY_ID_REQUEST';
export const GET_CLASS_BY_ID_SUCCESS = 'GET_CLASS_BY_ID_SUCCESS';
export const GET_CLASS_BY_ID_FAILURE = 'GET_CLASS_BY_ID_FAILURE';

export const ADD_CLASS_REQUEST = 'ADD_CLASS_REQUEST';
export const ADD_CLASS_SUCCESS = 'ADD_CLASS_SUCCESS';
export const ADD_CLASS_FAILURE = 'ADD_CLASS_FAILURE';
